# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 5
    target-branch: "master"
    commit-message:
      prefix: "[upd] pypi:"

  - package-ecosystem: "npm"
    directory: "/searx/static/themes/simple"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 5
    target-branch: "master"
    commit-message:
      prefix: "[upd] npm:"
