name: "Checker"
on:
  schedule:
    - cron: "0 4 * * 5"
  workflow_dispatch:

jobs:
  checker:
    name: Checker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ubuntu packages
        run: |
          sudo ./utils/searxng.sh install packages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install Python dependencies
        run: |
          make V=1 install

      - name: Checker
        run: |
          make search.checker
